coins/urls.py
from django.urls import path
from django.views.generic import TemplateView, FormView, View, ListView
from . views import IndexView, ExchangeRateView

app_name = 'coins'
urlpatterns = [
    path('', IndexView.as_view(), name = 'home'),
    path('exchange/', TemplateView.as_view(template_name='exchange.html'), name='exchange'),

]

psalm/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coins.urls', namespace='coins'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coins/models.py
from django.db import models

# Create your models here.

coins/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, View, ListView

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class ExchangeRateView(View):
    """
    Displaying the exchange rate based on the amount.
    If no amount entered will take the minimum transaction amount
    """
    def post(self, request, *args, **kwargs):
        convert_from = CURRENCY[request.POST.get('from')]
        convert_to = CURRENCY[request.POST.get('to')]
        amount = request.POST.get('amount')
        
        if amount:
            params =  {
                    "from": convert_from,
                    "to": convert_to,
                    "amount": amount
                }
            method = "getExchangeAmount"
        else:
            params =  {
                    "from": convert_from,
                    "to": convert_to,
                }
            method = 'getMinAmount'
        data = changelly_transaction(method,params)
        if not data.get('error'):
            request.session['convert_from'] = convert_from
            request.session['convert_to'] = convert_to
            request.session['amount'] = amount
            if not amount:
                request.session['amount'] = '1'
        return HttpResponse(json.dumps(data), content_type='application/json')

templates/base.html
<!DOCTYPE html> {% load static %}

<html>

<head>
    <title>Psalm.io</title>
    <meta charset="utf-8">
    <!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<![endif]-->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/crypto_custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <!--[if lt IE 9]>
		<script src="{% static 'js/vendor/html5shiv.min.js' %}"></script>
		<script src="{% static 'js/vendor/respond.min.js' %}"></script>
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
	<![endif]-->
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>

<body>
    <div class="preloader">
        <div class="preloader_image"></div>
    </div>
    <div class=" bg-blue p-4 d-md-flex justify-content-around">
        <div class="col-md-3  ">
            <span style="font-weight:600; font-size:24px">Psalm.io</span>
        </div>
        <div class="col-md-3 d-flex flex-row justify-content-around">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ request.user.first_name}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right nav-bg-dark" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="">Wallet</a>
                        <a class="dropdown-item" href="">Transactions</a>
                        <a class="dropdown-item" href="">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="">Log out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <a class="nav-item nav-link" href="">
                <span class="white-font bit-font">
                    <i class="fa fa-user "> </i> LOGIN</span>
            </a>
            <a class="nav-item nav-link " href="">
                <span class="white-font bit-font">
                    <i class="fa fa-sign-in "> </i> SIGNUP</span>
            </a>


            {% endif %}
        </div>
    </div>
    <nav class="navbar navbar-expand-lg nav-darkblue crypto-nav sticky-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars" aria-hidden="true"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbar-nav text-uppercase mr-auto">
                <a class="nav-item nav-link active" href="">home</a>
                <a class="nav-item nav-link" href="{% url 'coins:exchange' %}">Exchange</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link " href="">Wallet</a>
                    <a class="nav-item nav-link " href="">Transactions</a>
                {% endif %}

                <!-- {% if  user.is_authenticated %}

                <a class="nav-item nav-link" href="#">Logout</a>

                {% else %}
                <a class="nav-item nav-link" href="#">Signup</a>
                <a class="nav-item nav-link " href="#">Login</a>
                {% endif %} -->


            </div>

        </div>
    </nav>

    <!-- section caraousel-->
    <div class="col-12 pad0 slide-bg">

        {% block carousel%} {% endblock carousel %}
    </div>
    {% block content_wallet %} {% endblock content_wallet %}
    <!-- end caraousel -->
    <div class="container-fluid">
        <div class="row">
            {% block content %} {% endblock content%}
        </div>
    </div>
    <!-- section about bitcoin -->

    <section class=" footer">
        <div class=" bg-black p-5">
            <div class="col-12 p-3">
                <span>Access your Bitcoin Wallet securely</span>
            </div>
            <div class="col-12 p-3">
                <span class="footer-bold sansthick">biT-Exchange on all your devices</span>
            </div>
            <div class="col-12 p-3">
                <img class="img-fluid mt-1" src="{% static 'images/theme/appstore.png' %}">
                <img class="img-fluid mt-1" src="{% static 'images/theme/playstore.png'%}">
            </div>
        </div>
        <div class=" p-5 bg-navyblue">
            <div class="row col-md-10 offset-md-1 text-left">

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">About Us</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">Legal & Security</a>
                        </li>
                        <li>
                            <a href="#">Help Centre</a>
                        </li>
                        <li>
                            <a href="#">Terms of Use</a>
                        </li>
                        <li>
                            <a href="#">Refund Policy</a>
                        </li>
                        <li>
                            <a href="#">Press</a>
                        </li>
                    </ul>
                </div>

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">Services</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">Buy Bitcoin</a>
                        </li>
                        <li>
                            <a href="#">Buy Ethereum</a>
                        </li>
                        <li>
                            <a href="#">Sell Bitcoins</a>
                        </li>
                        <li>
                            <a href="#">Bitcoin Trading</a>
                        </li>
                        <li>
                            <a href="#">Margin Trading</a>
                        </li>
                    </ul>
                </div>

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">Information</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">Payment Options</a>
                        </li>
                        <li>
                            <a href="#">Fee Schedule</a>
                        </li>
                        <li>
                            <a href="#">Getting Started</a>
                        </li>
                        <li>
                            <a href="#">Identity Verification Guide</a>
                        </li>
                        <li>
                            <a href="#">Card Verification Guide</a>
                        </li>
                    </ul>
                </div>

                <div class="col-sm-6 col-md-3 p-3">
                    <span class="footer-header">Contact Us</span>
                    <div class="footer-header-line"></div>
                    <ul class="mt-3">
                        <li>
                            <a href="#">info@Coinzel.net
                            </a>
                        </li>
                        <li>
                            <a href="#">press@coinzel.net </a>
                        </li>
                        <li>
                            <a href="#">support@coinzel.net</a>
                        </li>
                        <li>
                            <a href="#">complaints@coinzel.net </a>
                        </li>
                        <li>
                            <a href="#">+44 20 8133 5474</a>
                        </li>
                    </ul>
                </div>



            </div>
        </div>



    </section>

    <div class="p-3 p-sm-0 d-flex  justify-content-around align-items-center bg-lightblue">
        <div class="col-12 col-md-4 mt-2">
            <div class="col-12 col-sm-8 offset-sm-2  d-flex justify-content-around align-items-center p-2">
                    <div class="fsc">
                            <i class="fa fa-facebook p-2" aria-hidden="true"></i>
                        </div>
                        <div class="fsc">
                            <i class="fa fa-twitter  p-2" aria-hidden="true"></i>
                        </div>
                        <div class="fsc">
                            <i class="fa fa-linkedin p-2 " aria-hidden="true"></i>
                        </div>
                        <div class="fsc">
                            <i class="fa fa-github  p-2" aria-hidden="true"></i>
                        </div>
            </div>
                
        </div>
        <div class="col-12 col-md-4 mt-2 text-center">
            <span class=" white-font sansthick">Copyright by biT-Exchange Ltd 2017.
                </span>
        </div>
        <div class="col-12 col-md-4 mt-2 text-center">
            <span class="margin-center"><img class="img-fluid"  src="{% static 'images/theme/bankicons.png' %}"></span>
        </div>
    </div>



    <!-- script -->
    <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/custom_crypto.js' %}"></script>
      {% block script %} {% endblock script %}

</body>

</html>

templates/exchange_confirm.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="">
	<div class="p-1 p-sm-5">
		<div class="row">
			<div class="col-sm-6 text-center p-5 row">
				<h2 class="exchange-confirm-font margin-center">You are converting from </h2> 
				
				<div class="col-5 col-md-5  text-center ">
						
						<img src="{% static 'img/coins/btc.png'%}" class="img-fluid">
						<br>
						<h3>btc</h3>
				</div>
				<div class="col-2 col-md-2 d-flex align-content-center mt-auto mb-auto flex-wrap text-center ">

						<span class="fa fa-exchange exchangefa margin-center"></span>
				</div>
				<div class="col-5 col-md-5 text-center ">
						<img src="{% static 'img/coins/ltc.png'%}" class="img-fluid">
						<br>
						<h3>ltc</h3>
				</div>
			</div>
			<div class="col-sm-6 p-5 exchange-border-left">
				<form class="contact-form row columns_padding_10 text-center" method="post" action="./">
					<h1>Enter your {{ request.session.convert_to }} wallet address you like to transfer</h1>
					{% if error %}
					<p>{{error}}</p>{% endif %} {% csrf_token %}
					<div class="col-sm-12">
						<div class="form-group bottommargin_0">
							<label for="name">
								<span class="required">Address*</span>
							</label>
							<input type="text" aria-required="true" size="30" value="" name="transaction_from" id="id_transaction_from" class="form-control exchange-input"
							    placeholder="{{ request.session.convert_to }} Address">
							<span>
								<p> {{ form.errors.transaction_from }}</p>
							</span>
						</div>
					</div>
					
					<div class="col-sm-12">
						<div class="form-group bottommargin_0">
							<label for="name">Amount
								<span class="required">*</span>
							</label>
							<span class="exchange-amount">{{ request.session.amount }}</span>
							<span>
								<p> {{ form.errors.amount }}</p>
							</span>
						</div>
					</div>
					<div class="col-sm-12">
						<div class="contact-form-submit topmargin_20">
							<button type="submit" name="contact_submit" class="btn btn-secondary exchange-next">Next</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/pay_in.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="col-12">

			<div class="col-sm-6 offset-sm-3 text-center ">
				<img src="https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl={{address}}"></img>
				<h3> Please pay to the following address from your wallet</h3>
				<h4>{{ address }}</h4>
            </div>

</section>
{% endblock %}

templates/transactions.html
{% extends 'base.html' %} {% load transaction_status %} {% load static %} {% block content %}
<section class="col-12">

	<div class="table-responsive">
		<table class="table table_template darklinks table-striped table-bordered table-hover" id="timetable">
			<thead>
				<tr>
					<th>Status</th>
					<th>User</th>
					<th>From currency</th>
					<th>To Currency</th>
					<th>Amount</th>
					<th>Transaction ID</th>
					<th>Transaction From</th>
					<th>Transaction To</th>
				</tr>
			</thead>
			<tbody>

					{% for obj in object_list %}
				<tr>
					<td>{% transaction_status obj.transaction_id %}</td>
					<td>{{obj.user}}</td>
					<td>{{obj.from_currency}}</td>
					<td>{{obj.to_currency}}</td>
					<td>{{obj.amount}}</td>
					<td>{{obj.transaction_id}}</td>
					<td>{{obj.transaction_from}}</td>
					<td>{{obj.transaction_to}}</td>
				</tr>
				{% endfor %}

			</tbody>
		</table>
	</div>

</section>
{% endblock content %}

templates/wallets.html
{% extends 'base.html' %} {% load static %} {% load transaction_status %} {% block content %}
<div class="page-header-dark col-12">
	<h1 class="page-header-font-yellow">Wallets</h1>
	<div class="breadcrumbs-dark">
		<span>Home</span>
		<span>/</span>
		<a href="">
			<span>Wallets</span>
		</a>
	</div>
</div>
<div class="col-10 offset-1 mt-5">
	<div class="row">
{% for obj in request.user.wallets.all %}
			<!-- card -->
			<div class="col-12 col-sm-6 col-md-4 col-lg-3 p-3">
				<div class="wallets">
					<div class="col-12 text-center p-3">
						<img src="{% static 'img/coins/'%}{{obj.name}}.png" class="img-100">
						<h3>{{ obj.name }}</h3>
					</div>
					<div class="col-12 dont-break-out">
						<label>Address:</label>
						<div class="bg-grey">
							<h5>{{obj.address}}</h5>
						</div>
					</div>
					<div class="col-12 dont-break-out">
						<label>Balance:</label>
						<div class="bg-grey">
							{% if obj.name == 'btc' %}
							    <h5>{% get_bit_balance obj.address request.user.username %}</h5>
							{% elif obj.name == 'eth' %}
							    <h5>{% get_eth_balance obj.address %}</h5>
                            {% elif obj.name == 'btg' %}
							    <h5>{% get_btg_balance obj.address %}</h5>
							{% elif obj.name == 'ltc' %}
							    <h5>{% get_ltc_balance obj.address %}</h5>
							{% else %}
							<h5>0</h5>
							{% endif %}
						</div>
					</div>
					<!-- <div class="col-12 dont-break-out">
						<label>Equivalent USD:</label>
						<div class="bg-grey">
							<h5>13,547.4000 USD</h5>
						</div>
					</div> -->
				</div>
			</div>
			<!-- card-end -->
			{% endfor %}
	</div>
</div>

{% endblock %}

templates/welcome.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="col-sm-12 text-center">
	<h2>Welcome <span class="page-header-font-yellow">{{request.user.first_name}}</span> </h2>
</div>

<section class="col-12">

			<h3 class="">Name: {{request.user.first_name}} {{request.user.last_name}}</h3>
			<h3 class="">Email: {{request.user.email}}</h3>
			<a href="{% url 'logout' %}"> Logout </a>

</section>

<section class="col-12 text-center">
	<!-- market_cap -->
				<h3>CryptoCurrency Market Capitalizations</h3>

				<!-- hanya muncul ketika md dan lg -->
				<div class="d-none d-md-block col-md-10 offset-md-1">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Name</th>
								<th>
									<div class="pull-right">
										Market Cap
									</div>
								</th>
								<th>
									<div class="pull-right">
										Price
									</div>
								</th>
								<th>
									<div class="pull-right">
										Circulating Supply
									</div>
								</th>
								<th>
									<div class="pull-right">
										Volume (24h)
									</div>
								</th>
							</tr>
						</thead>

						<tbody id="marketcap_tbody">

						</tbody>

					</table>
				</div>

				<!-- hanya muncul ketika sm dan xs -->
				<div class="d-md-none d-lg-none d-xl-none bg-dark">
					<div id="marketcap_tbody_small" class="p-5">

					</div>
				</div>

	<!-- end market_cap -->



</section>
{% endblock %} {% block script %}
<script type="text/javascript">
    Number.prototype.numberFormat = function(decimals, dec_point, thousands_sep) {
        dec_point = typeof dec_point !== 'undefined' ? dec_point : '.';
        thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : ',';

        var parts = this.toFixed(decimals).split('.');
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

        return parts.join(dec_point);
    }
    </script>
<script type="text/javascript">
	// get list dari coinmarketcap
	function getMarketCap() {

		$.ajax({
			url: 'https://api.coinmarketcap.com/v1/ticker/?limit=10',
			success: function (response) {

				$('tbody#marketcap_tbody').html('');

				$.each(response, function (a, b) {

					$('tbody#marketcap_tbody').append(
						'<tr>' +
						'    <td>' +
						'        ' + b.rank +
						'    </td>' +
						'    <td>' +
						'        ' + b.name +
						'    </td>' +
						'    <td align="right">' +
						'        $ ' + parseFloat(b.market_cap_usd).numberFormat(1, ".", ",") +
						'    </td>' +
						'    <td align="right">' +
						'        $ ' + parseFloat(b.price_usd).numberFormat(5, ".", ",") +
						'    </td>' +
						'    <td align="right">' +
						'        ' + parseFloat(b.available_supply).numberFormat(1, ".", ",") + ' ' + b.symbol +
						'    </td>' +
						'    <td align="right">' +
						'        $ ' + parseFloat(b['24h_volume_usd']).numberFormat(1, ".", ",") +
						'    </td>' +
						'</tr>'
					);

					$('div#marketcap_tbody_small').append(
						'<div style="border-top: 1px solid #fff; padding: 10px auto; margin: 10px auto;">' +
						'    <div class="pt5"><label>Rank</label>:<div>' + b.rank + '</div></div>' +
						'    <div class="pt5"><label>Name</label>:<div>' + b.name + '</div></div>' +
						'    <div class="pt5"><label>Market Cap</label>:<div>' + '$ ' + parseFloat(b.market_cap_usd).numberFormat(1,
							".", ",") + '</div></div>' +
						'    <div class="pt5"><label>Price</label>:<div>$' + parseFloat(b.price_usd).numberFormat(5, ".", ",") +
						'</div></div>' +
						'    <div class="pt5"><label>Circulating Supply</label>:<div>' + parseFloat(b.available_supply).numberFormat(
							1, ".", ",") + ' ' + b.symbol + '</div></div>' +
						'    <div class="pt5"><label>Volume (24h)</label>:<div>$' + parseFloat(b['24h_volume_usd']).numberFormat(1,
							".", ",") + '</div></div>' +
						'</div>'
					);
				});
			}
		});
	}

	(function(){
        // atur menu
        $('.n-menu_dashboard').addClass('active');
        /* ambil data dari coinmarketcap */
        getMarketCap();

        // eksekusi semua crypto balance by interval dan juga data dari coinmarketcap
        setInterval(function(){
            getBtcBalance();
            
            
            

            getMarketCap();
        }, 120000);

    })()
</script>

{% endblock %}